### ISSUE TITLE
How can we run training?

### ISSUE THREAD

**Issue by soskek** [timojl/clipseg#1]
Thank you for releasing the great code! I enjoyed the notebook a lot.

By the way, can we train a model from scratch or fine-tuning?
Although I read `experiment_setup.py`, I didn't find how to run the training directly.

**Comment by timojl** [comment]
Thanks for the question! Training is implemented in train_loop in experiment_setup.py with the training configuration being specified in experiments/phrasecut.yaml. 
We plan to describe training in more detail later.

**Comment by soskek** [comment]
Thank you!
I’m looking forward to using the full codebase!

**Comment by soskek** [comment]
I wrote some missing features for reminders.

---

e.g. madpack (?) may be missing. 

https://github.com/timojl/clipseg/blob/master/datasets/phrasecut.py#L2
```
from madpack.transforms.spatial import random_crop_slices
```

**Comment by soskek** [comment]
`TrainingLogger` in general_utils.py seems broken or old.

https://github.com/timojl/clipseg/blob/master/experiment_setup.py#L162
```
    with TrainingLogger(log_dir=config.name, interval=150, model=model, config=tracker_config, utilization_iters=500) as logger:
```

caused
```
TypeError: __init__() got an unexpected keyword argument 'interval'
```
and
```
AttributeError: __enter__
```

**Comment by soskek** [comment]
`BinaryIoU` is missing in metrics.py

**Comment by timojl** [comment]
@soskek Thanks for pointing this out. We will address these issues when we update the codebase.

**Comment by qiulesun** [comment]
@timojl Could you provide training command to reproduce results ?

**Comment by timojl** [comment]
The code base has been updated. Training and evaluation should be straightforward now and the problems pointed out by @soskek (thanks, again) should be resolved.
