### ISSUE TITLE
Is there a way to set a seed?

### ISSUE THREAD

**Issue by Jetpackjules** [timojl/clipseg#10]
Trying to get the same output consitently for video frame-by-frame use. Can't find any sort of paramater/argument/function to call to set a custom seed...

**Comment by timojl** [comment]
The model output is deterministic (make sure `model.eval()` was called), there is no way to set a seed. Frame-by-frame inconsistencies might be due to the model being sensitive to small changes in the input. I never investigated this setting, though.
