### ISSUE TITLE
import error in clipseg.py

### ISSUE THREAD

**Issue by zyyyz** [timojl/clipseg#15]
On line 21 (models/clipseg.py) , I got an import error.  **from models.clip_prompts import imagenet_templates**
In fact , there has no file or function called _clip_prompts_ in the _models_ directory.
Thank you very much!

**Comment by timojl** [comment]
You are right, the module is missing. However, this setting was not used in the experiments. Hence, I removed the code you refer to. Originally, the idea was to use the CLIP's prompt variations shown here: https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb (cell 7). 
Thanks.
