### ISSUE TITLE
image with mask prompt for one shot

### ISSUE THREAD

**Issue by raymond1123** [timojl/clipseg#17]
Hi, great job! I realy love this CLIP based segment. 
I am not so familiar with the code right now, I am just wondering how can I use a image as a prompt ?

**Comment by timojl** [comment]
Thanks! Using an image prompt is quite easy: Just use an image instead of a prompt:
```python
# tensor shapes: img and another_img: [1, 3, 352, 352], mask: [1, 352, 352]
masked_img = another_img * mask  
# now, masked_img is an image where only relevant regions are visible, the rest is black.
model(img, masked_img)
```
Now CLIPSeg should segment the region in img that matches the masked region. 

Make sure that the images are properly normalized by:
`transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])`

**Comment by stephencheung16** [comment]
Hi, I tried but the result does not look good.  Would you please help?  Thanks.

![code](https://github.com/timojl/clipseg/assets/23723498/8f340800-d42f-492b-a3cd-5cf46a2fcc4b)

![result](https://github.com/timojl/clipseg/assets/23723498/484dfdc8-3c75-4cf5-a0e7-3760ea174fe9)
