### ISSUE TITLE
How to download PhraseCut.tar?

### ISSUE THREAD

**Issue by ghost** [timojl/clipseg#19]
Thanks for your great job!

How can I get PhraseCut.tar in `phrasecut.py`?

**Comment by timojl** [comment]
Thanks for bringing this up! `PhraseCut.tar` is not directly available but must be composed by [downloading the PhraseCut dataset](https://github.com/ChenyunWu/PhraseCutDataset/blob/master/download_dataset.py). PhraseCut.tar should have this structure:
```
VGPhraseCut_v0/name_att_rel_count.json
VGPhraseCut_v0/image_data_split.json
VGPhraseCut_v0/refer_miniv.json
VGPhraseCut_v0/refer_input_val.json
VGPhraseCut_v0/refer_test.json
VGPhraseCut_v0/refer_train.json
VGPhraseCut_v0/refer_input_miniv.json
VGPhraseCut_v0/refer_input_test.json
VGPhraseCut_v0/refer_val.json
VGPhraseCut_v0/refer_input_train.json
VGPhraseCut_v0/images/... <- here are the images from Visual Genome
```
