### ISSUE TITLE
Evaluated on referring image seg datasets on RefCOCO, RefCOCO+ , and G-Ref 

### ISSUE THREAD

**Issue by qiulesun** [timojl/clipseg#2]
@timojl  
Nice work!
In the field of referring image seg, RefCOCO, RefCOCO+ , and G-Ref are wided commonly datasets to evaluate proposed method and compare with others, e.g., the new CVPR 2022 paper CRIS: CLIP-Driven Referring Image Segmentation, which is also  based on CLIP. Do you  plan to report results on these datasets or provide corresponding scripts in your repo. to achieve that by readers themselves ?

**Comment by timojl** [comment]
Thank you for this suggestion. Currently we do not plan reporting results on these datasets. However, interested users could conduct these experiments by extending score.py based on the example of the other datasets.
