### ISSUE TITLE
Import error in pfe_dataset.py

### ISSUE THREAD

**Issue by hwanyu112** [timojl/clipseg#21]
In `pfe_dataset.py` line 5 :
`from datasets.lvis_oneshot3 import blend_image_segmentation`
I can not find the `lvis_oneshot3.py` file, Thanks!
Beside, how can I run the zero-shot experiment?

**Comment by timojl** [comment]
I fixed the import error. For running zero-shot segmentation, see [Quickstart.ipynb](https://github.com/timojl/clipseg/blob/master/Quickstart.ipynb). For training, see training.py main function.
