### ISSUE TITLE
Fine-tune Clipseg

### ISSUE THREAD

**Issue by nimakasipour** [timojl/clipseg#23]
Thanks for the great work! I am writing my master's thesis and would like to use your model for my work, as I already evaluated it on the coco eval2017 dataset and the results are good. I would like to refine the model "CIDAS/clipseg-rd64-refined" for my work, do you have any tutorial on how I can Fine-tune the model, or do you have some tips for me to get started?

**Comment by timojl** [comment]
Thanks for your interest in CLIPSeg. I suggest to modify `training.py` and adapt it to your needs. You can initialize the model with the pre-trained weights by `model.load_state_dict()`. Depending on the size of your fine-tuning dataset, you might want to freeze (.requires_grad = False) additional parameters.
