### ISSUE TITLE
Can you provide an example script for this task - extracting clothes

### ISSUE THREAD

**Issue by FurkanGozukara** [timojl/clipseg#24]
We give an input image, mask text, and then it will extract that masked area from the image and save into a folder

I have used invoke ai but the results are not like i am expecting

input

![a.jpg](https://s3.amazonaws.com/moonup/production/uploads/1676290094538-6345bd89fe134dfd7a0dba40.jpeg)

command

!mask "C:\Users\King\Downloads\a.jpg" -tm "clothes" 0.99

outputs

![image.png](https://s3.amazonaws.com/moonup/production/uploads/1676290126401-6345bd89fe134dfd7a0dba40.png)

![image.png](https://s3.amazonaws.com/moonup/production/uploads/1676290136953-6345bd89fe134dfd7a0dba40.png)

my expected output

![image.png](https://s3.amazonaws.com/moonup/production/uploads/1676290153996-6345bd89fe134dfd7a0dba40.png)

**Comment by timojl** [comment]
For example code of how to use the model with text input see `Quickstart.ipynb`.
I cannot comment on issues with invoke ai. Possibly the image is too large (in the example we use 352px) or the value range is not properly normalized, but these are just guesses.

**Comment by FurkanGozukara** [comment]
> For example code of how to use the model with text input see `Quickstart.ipynb`. I cannot comment on issues with invoke ai. Possibly the image is too large (in the example we use 352px) or the value range is not properly normalized, but these are just guesses.

i will test that. is the image has to be 352x352 exactly?

**Comment by timojl** [comment]
no, any multiple of 16 is fine.
