### ISSUE TITLE
Reproducing `uni-rd64-refined.pth` weights

### ISSUE THREAD

**Issue by helen1c** [timojl/clipseg#25]
Hi @timojl, amazing work, thanks for sharing. :)

Could you please tell me which `configuration` from `individual_configurations` produced `uni-rd64-refined` weights?

**Comment by timojl** [comment]
Glad you like the project and thanks for bringing this up! 

The key change is setting `complex_trans_conv` to `True`. The refined model was also trained for 50,000 iterations and uses a dropout of `0.1` in all transformer layers (`self.blocks` and `self.extra_blocks` in `models/clipseg.py`). The latter is currently not implemented here and must be set by editing code. I updated the experiments: https://github.com/timojl/clipseg/blob/master/experiments/phrasecut.yaml#L74

**Comment by helen1c** [comment]
During training `extra_blocks` variable is set to 0?
It seems to me that default dropout value used is `0.1`. So, basically code does not need any changes?

![image](https://user-images.githubusercontent.com/66186741/221556371-36c24bb3-7d1c-4770-88a5-fa1223b2c95d.png)

And the second question, should I possibly use `PhraseCutPlus` dataset class instead of `PhraseCut` class?

**Comment by timojl** [comment]
Right, no change needed for this. The `uni-rd64-refined` configuration used the regular `PhraseCut` dataset.
