### ISSUE TITLE
Difference in PhraseCut images number

### ISSUE THREAD

**Issue by helen1c** [timojl/clipseg#26]
Hi @timojl,

![image](https://user-images.githubusercontent.com/66186741/221522795-d56ffd92-ff3a-4836-83b2-a4acc96dcce7.png)
This integrity check fails for me, because number of PhraseCut images I downloaded is `78802` (wrt `108250` as you stated in the code). Do you know how that difference came about?
 
To download the `PhraseCut dataset` I used the `download_dataset` script from the `PhraseCutDataset` repository, just like you mentioned in one of the closed issues.

**Comment by timojl** [comment]
This integrity check is part of our internal tools. I assume that I put all images from VisualGenome into the archive (but only used the ones that are labelled in PhraseCut for training). Hence, you can ignore the integrity check.
