### ISSUE TITLE
Missing imports in `Tables.ipynb` and `Visual_Feature_Engineering.ipynb`

### ISSUE THREAD

**Issue by helen1c** [timojl/clipseg#27]
Hi @timojl,

could you please review (and possibly resolve) missing imports in `Tables.ipynb` (`from datasets.lvis_oneshot3 import LVIS_OneShot3, LVIS_OneShot`, `experiment` function) and `Visual_Feature_Engineering.ipynb` (`from datasets.lvis_oneshot3 import LVIS_OneShot3`, `plot_data`, `transforms`)?

**Comment by timojl** [comment]
The LVIS Oneshot dataset code is only required for the visual feature engineering experiment and unfortunately not very clean. Therefore I decided to exclude it from this repository. However, there older commits still include the file, you can find it here: https://github.com/timojl/clipseg/blob/d47c2974b4eb2603d9b2d3a83c40bf565939919f/datasets/lvis_oneshot3.py
