### ISSUE TITLE
LICENSE of this repository

### ISSUE THREAD

**Issue by stes** [timojl/clipseg#3]
Hi @timojl , thanks for sharing this! I was wondering if you were planning to add an open-source `LICENSE` to the repository (as of now [exclusive copyright](https://choosealicense.com/no-permission/) would apply to the repo). Thanks for considering :)

**Comment by timojl** [comment]
Hi @stes, sorry for the delay. I just updated the repository (excluding weights) to be MIT licensed. Thanks for pointing this out.
