### ISSUE TITLE
Weights for ViT-B/32 version of CLIPDensePredT

### ISSUE THREAD

**Issue by rvignav** [timojl/clipseg#34]
Hi @timojl, amazing paper! Had a quick question about whether pretrained weights for the CLIPSeg decoder are released for the ViT-B/32 version of CLIP. I see many tutorials with the following code:
```
os.system("wget https://owncloud.gwdg.de/index.php/s/ioHbRzFx6th32hn/download -O weights.zip")
os.system("unzip -d weights -j weights.zip")
model = CLIPDensePredT(version='ViT-B/16', reduce_dim=64)
model.load_state_dict(torch.load('weights/rd64-uni.pth', map_location=torch.device('cpu')), strict=False)
```
But I can't find any corresponding weights for the ViT-B/32 version.
Would really appreciate help on this. Thanks!

**Comment by timojl** [comment]
Hi Vignav, 
we used the ViT-B/32 versions during development when the /16 weights weren't released yet. However, all recent models were trained on the ViT-B/16 version, so unfortunately I cannot provide useful /32 weights.
That being said, depending on your use case, using less tokens with the /16 weights might actually work well. You might need to adapt the positional encoding, though.

**Comment by rvignav** [comment]
Got it - thanks @timojl! Would you be able to help with adapting positional encoding / using the /16 weights in conjunction with a /32-based CLIP model? The code below produces the following error:
```
os.system("wget https://owncloud.gwdg.de/index.php/s/ioHbRzFx6th32hn/download -O weights.zip")
os.system("unzip -d weights -j weights.zip")
model = CLIPDensePredT(version='ViT-B/32', reduce_dim=64)
model.load_state_dict(torch.load('weights/rd64-uni.pth', map_location=torch.device('cpu')), strict=False)
```

```
RuntimeError: Error(s) in loading state_dict for CLIPDensePredT:
	size mismatch for trans_conv.weight: copying a param with shape torch.Size([64, 1, 16, 16]) from checkpoint, the shape in current model is torch.Size([64, 1, 32, 32]).
```

**Comment by timojl** [comment]
Probably it won't work this way. The solution I propose is using CLIP ViT-B/16 and the rd64-uni weights but using less tokens by reducing the input image size. CLIPSeg can operate at different resolutions (and thus different numbers of internal tokens), e.g. at only 128x128:
```
model = CLIPDensePredT(version='ViT-B/16', reduce_dim=64)
model.load_state_dict(torch.load('weights/rd64-uni.pth', map_location=torch.device('cpu')), strict=False)
model(torch.zeros(1,3,128,128).cuda(), 'a car')[0].shape
```
If you don't like the input image size reduction, you could `nnf.interpolate` `model.model.conv1.weight` from 16x16 to 32x32 and finetune from there. Something similar could be done on `model.trans_conv` to obtain high-resolution output.

**Comment by rvignav** [comment]
I see. The issue is, I am replacing the CLIP weights with that of a different CLIP-style model (with ViT-B/32 structure) and using CLIPSeg's pretrained decoder to run experiments. Given this requirement, may I ask you to elaborate on this/potentially provide any code:

"If you don't like the input image size reduction, you could nnf.interpolate model.model.conv1.weight from 16x16 to 32x32 and finetune from there. Something similar could be done on model.trans_conv to obtain high-resolution output."

**Comment by timojl** [comment]
In that case this won't work. CLIPSeg is trained to read out activations of a specific CLIP model (ViT-B/16), therefore replacing the underlying CLIP model will break CLIPSeg.
