### ISSUE TITLE
Object Not Present 

### ISSUE THREAD

**Issue by PerrinAntonin** [timojl/clipseg#37]
Hi! Well done for this very interesting work!
Do you know is there is particular way of detecting if the object is not present in the image? (by "detecting" I mean with a threshold, for example)

**Comment by timojl** [comment]
Ideally, the output mask should be empty if the object is not present. Alternatively, you could use CLIP (without seg) to build a zero-shot classifier over object presence, i.e. computing a probability distribution over [image contains [obj], image does not contain [obj].
