### ISSUE TITLE
image with mask prompt for one shot (revisit)

### ISSUE THREAD

**Issue by stephencheung16** [timojl/clipseg#38]
Hi, I tried but the result does not look good. Would you please help? Thanks.

![result](https://github.com/timojl/clipseg/assets/23723498/fed9beb8-e2b0-4144-bc55-c254473f4218)

![code](https://github.com/timojl/clipseg/assets/23723498/a10f453d-317f-4b56-9698-cb0ccc0cbd27)

**Comment by stephencheung16** [comment]
After reloading the weights, it looks better.  But it still does not detect the spoon correctly.

![result_1](https://github.com/timojl/clipseg/assets/23723498/ee03afb6-67ea-4bf2-b97d-4c0f73a1594f)

**Comment by timojl** [comment]
Providing a one-shot visual support image is more challenging than the providing the label name as text. I would not expect it work all the time. Possibly, you might want to double check that your images are properly normalized.
