### ISSUE TITLE
Quickstart notebook and refined weights

### ISSUE THREAD

**Issue by pivpiv** [timojl/clipseg#40]
Hi, thank you for your work. 
When I try to modify the Quickstart notebook to load refined wieghts : 
`model.load_state_dict(torch.load('weights/rd64-uni-refined.pth', map_location=torch.device('cpu')), strict=False);`
I get weird results 
![image](https://github.com/timojl/clipseg/assets/13489077/11bfa653-2a7b-491a-b3a4-2c9b66c88cb6)
How do I modify the code when using refined weights?
Thanks

**Comment by timojl** [comment]
Please make sure that:
- You initialize the model correctly for the refined weights: 
`model = CLIPDensePredT(version='ViT-B/16', reduce_dim=64, complex_trans_conv=True)`
- The model weights were correctly download. This is the sha1 checksum: `8a3824a4f447096af25a00f9ac80b50e13cace63`

Let me know if this doesn't help!
