### ISSUE TITLE
Performance on Pascal-5i one-shot 

### ISSUE THREAD

**Issue by jingyi1997** [timojl/clipseg#41]

**Comment by jingyi1997** [comment]
Hi! Thanks for the work and sharing the code.

I have a question regarding the performance on Pascal-5i one-shot setting. In order to reproduce the numbers in the paper, do I need to re-trained the model by removing the unseen classes for each split?

**Comment by timojl** [comment]
Thanks for your interest in our work! 
The scores in the paper were obtained by training on PhraseCut and testing on Pascal5i. For each split, the test classes must be removed from the PhraseCut training dataset. This is defined here: https://github.com/timojl/clipseg/blob/master/datasets/phrasecut.py#L21
