### ISSUE TITLE
Missing __init__.py file causes import errors

### ISSUE THREAD

**Issue by scott-createplay** [timojl/clipseg#44]
Hey! Great package. 

I am using this with the Masquerade-Nodes for comfyui, but on install it complains: "clipseg is not a module".

I found that the clipseg directory doesn't have an `__init__.py` file in it. Adding this fixed the import issue.

![image](https://github.com/timojl/clipseg/assets/42323367/616c4c52-94de-4de4-84ff-d2ebd38bc1c1)

**Comment by timojl** [comment]
Thanks for pointing out this issue. I added the __init__.py
