### ISSUE TITLE
Missing file category_info.json

### ISSUE THREAD

**Issue by JUSTUSVMOS** [timojl/clipseg#46]
HI, Thanks for your great job!. Could you please provide details on the structure of the LIVS_OneShot3b.tar file, or guidance on how to obtain the missing "category_info.json" file? Your assistance in this matter would be greatly appreciated!

**Comment by timojl** [comment]
Thank you and sorry for the delay. The `category_info.json` should contain the mapping from LVIS object category ids to their names (from the LVIS annotation json). It has this format: `[{"name": "aerosol_can", "id": 1}, ...]`.
