### ISSUE TITLE
Error Running scope.py: 'config.json' File Not Found in Logs Directory

### ISSUE THREAD

**Issue by nguyenphuc22** [timojl/clipseg#47]
**Error Description:**
I followed all the setup instructions as mentioned in the readme file. However, when I attempt to run `python scope.py coco.yml 0 0`, I encounter an error indicating that the 'config.json' file is missing from the 'logs' directory.

**Steps to Reproduce:**
1. Set up the environment according to the guidelines.
2. Execute the command `python scope.py coco.yml 0 0`.

**Expected Result:**
The program should run without encountering any errors.

**Actual Result:**
An error message appears stating that the 'config.json' file cannot be found in the 'logs' directory.

**Additional Notes:**
I have searched through the documentation and previous issues but could not find any references to this 'config.json' file. Please provide guidance on how to resolve this issue.

**Comment by timojl** [comment]
Sorry about the late response. The config.json file describes the training configuration and is created while training. For running the score.py file it should be sufficient to put the correct model parameters in the config.json file. Without having tested it, this might work for the `rd64-uni-refined.pth` checkpoint:
config.json: `{"model": "models.clipseg.CLIPDensePredT", "version": "ViT-B/16", "reduce_dim": 64, "complex_trans_conv": true}`
