### ISSUE TITLE
What should I change if i want to train a new keypoint detection detection?

### ISSUE THREAD

**Issue by bw2497** [timojl/clipseg#51]
I want to train the model to get the human's joint position more accureately by training a new dataset. I want to know what should I do if I want to use a new dataset.

**Comment by timojl** [comment]
While the model was not designed for pose estimation, to change the dataset you have to modify the `training.py` script. This could be a starting point: https://github.com/timojl/clipseg/blob/master/training.py#L84C1-L87C42 but more modifications will be needed.
