### ISSUE TITLE
Could you please share "all_splits.json" file?

### ISSUE THREAD

**Issue by afountain** [timojl/clipseg#53]
Thanks for your contribution, when using lvis db, there is "lvis_sample_areas.pickle" required, could you please share the file with me or share an example data structure of this file?
Thanks in advance.

**Comment by timojl** [comment]
Thanks for your question. From what I remember it should indicate the sizes of the objects (in terms of relative image space occupied). I think the file contains a dictionary that maps from (image_id, object_id) (both as string) to the respective size (as float). Most likely you can just ignore the file.
`all_splits.json` indicates the assignment to training and test sets for LVIS classes.
