### ISSUE TITLE
Increasing the resolution of the mask

### ISSUE THREAD

**Issue by remybonnav** [timojl/clipseg#8]
So when I run the code I get a mask that seems to be made of 32x32 large square on a whole 512x512 pixels image.

Is there a way to increase the resolution of the prediction and thus the mask generated?

Thanks a lot in advance.

**Comment by PancrasPZ** [comment]
Hi~ 
i'm also looking for the ways.
The low resolution seems due to the CLIP model...

So, i'm trying to find another way to help increase the resolution...
Such as, use the mask that create by CLIPSeg as a trimap and create the final high resolution mask with the other project..(like Deep-Image-Matting ?)

**Comment by remybonnav** [comment]
I have to try in automatic1111 webUi this code
https://github.com/ThereforeGames/txt2mask
to see if it is also limited to 512*512 and with low resolution or if they manage to increase it

**Comment by PancrasPZ** [comment]
I have already tried this, they use a simple Resize to increase the resolution..
I don't know is it suit for you.
In my case, the quality is not enough.
 

> I have to try in automatic1111 webUi this code https://github.com/ThereforeGames/txt2mask to see if it is also limited to 512*512 and with low resolution or if they manage to increase it

**Comment by timojl** [comment]
The problem that the binary segmentations have a block-like appearance is known and reported in the paper. I'll have a closer look into this problem and see if it can be improved.

**Comment by timojl** [comment]
Adding a convolution to consider the neighborhood before projecting into pixel space solves this problem to some degree, see the `complex_trans_conv` option in CLIPSeg model for details. The updated model and corresponding weights are available.
