### ISSUE TITLE
Unable to download weights

### ISSUE THREAD

**Issue by Jetpackjules** [timojl/clipseg#9]
**When I run:**
"! git clone https://github.com/timojl/clipseg"
**in google colab,**
**I get this error:**
Error downloading object: weights/rd16-uni.pth (61545cd): Smudge error: Error downloading weights/rd16-uni.pth (61545cdb3a28f99d33d457c64a9721ade835a9dfbda604c459de6831c504167a): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

**Here is the FULL ERROR:**
Cloning into 'clipseg'...
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 168 (delta 36), reused 39 (delta 16), pack-reused 91
Receiving objects: 100% (168/168), 1.21 MiB | 4.54 MiB/s, done.
Resolving deltas: 100% (77/77), done.
Downloading weights/rd16-uni.pth (1.1 MB)
Error downloading object: weights/rd16-uni.pth (61545cd): Smudge error: Error downloading weights/rd16-uni.pth (61545cdb3a28f99d33d457c64a9721ade835a9dfbda604c459de6831c504167a): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to /content/clipseg/clipseg/clipseg/.git/lfs/objects/logs/20220922T222731.926515854.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: weights/rd16-uni.pth: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by timojl** [comment]
Thanks for bringing this up. The problem is that the monthly LFS data transfer limit was exceeded. I removed the weights from the repository and put them to an external storage without limit. However, this makes obtaining the weights a little less convenient as a `wget` and an `unzip` call are necessary now.

**Comment by Jetpackjules** [comment]
Thanks so much!
